### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by f3l1x** [ViPErCZ/passwordRecovery#2]
Nove heslo by se prece nemelo posilat emailem, ne? :)

**Comment by ViPErCZ** [comment]
Ahoj. Prvně bych chtěl poděkovat, že vůbec někdo napsal a podíval se na to. Ani jsem to nečekal.
Děkuji za připomínku. Asi by jsme se divili kolik velkých portálů to ale takto dělá.
Osobně se rád přiučím čemukoliv, takže pokud mi poradíš, tak budu jen rád a zapracuji.

**Comment by f3l1x** [comment]
Muzes mrknout treba tady:
- https://forum.nette.org/cs/19859-posilani-prihlasovacich-udaju-emailem
- https://www.michalspacek.cz/prednasky/zahashovat-heslo-ulozit-profit-develcz

**Comment by ViPErCZ** [comment]
Pokud jsem to dobře pochopil, tak hlavní problém je v tom komu to heslo vlastně přijde.
Pokud se mi někdo dostane do schránky nebo si přečte data jako taková, tak prostě heslo nemůžeš poslat nikdy nikam.
Osobně se mi líbí ta myšlenka změny, kdy si uživatel zadá svoje heslo a tahle možnost je dočasná jen chvíli a nebo do doby samotné změny (záleží co nastaven dříve). A bezpečnější to je za předpokladu, že se mi do emailu nikdo nedostane teď, ale dva dny potom co mi přijde odkaz na změnu. Pokud někdo zachytí email ještě než mi přijde, tak si heslo může změnit ještě před samotným uživatelem. Takže vše stejně záleží na šifrování mail komunikace.
Výhoda je, že uživateli ve schránce zůstane neplatný odkaz a ne platné heslo, kdyby si to tam někdo v budoucnu přečetl. Jenže ten zase může vyvolat podle odkazu novou změnu hesla a heslo si tak změnit sám.
Pokud dobře analyzuji, pak šifrování email komunikace a neprolomený email účet je tak jako tak nutnost kvůli bezpečnosti.

Určitě zapřemýšlím nad tím jak udělat reset přes dočasný link. ;-)

**Comment by ViPErCZ** [comment]
Tak jsem to předělal tak, že nyní se odešle na email pouze odkaz s dočasným tokenem. Na odkaze se pak zobrazuje form pro zadání nového hesla. Po zadání nového hesla je odkaz opět nefunkční.
Ještě přemýšlím zda neudělat nějakou notifikační hlášku, když vyprší token. Něco jako, že zadaný token je nepletný. Ale to případně už nebude BC break jako nyní, ale pouze rozšíření. Ještě jednou za tip a uzavírám.
